FROM python:3.12.11-alpine3.22

ARG G2P_REF=v3.0.0

RUN apk add --no-cache --virtual .build-deps gcc libc-dev linux-headers make \
 && apk add --no-cache bash git gettext libpq-dev libmagic

WORKDIR /app

# Dynamic deps from workflow (optional)
COPY adapters.requirements.txt /tmp/adapters.requirements.txt
RUN if [ -s /tmp/adapters.requirements.txt ]; then pip install --no-cache-dir -r /tmp/adapters.requirements.txt --verbose; fi

# Core libs (as in your current API Dockerfile)
RUN pip install --no-cache-dir git+https://github.com/openg2p/openg2p-fastapi-common@v1.1.4\#subdirectory=openg2p-fastapi-common  \
 && pip install --no-cache-dir git+https://github.com/openg2p/openg2p-fastapi-common@v1.1.4\#subdirectory=openg2p-fastapi-auth \
 && pip install --no-cache-dir git+https://github.com/openg2p/openg2p-fastapi-common@v1.1.4\#subdirectory=openg2p-fastapi-auth-models \
 && pip install --no-cache-dir git+https://github.com/openg2p/openg2p-g2pconnect-common-lib@v2.0.0\#subdirectory=openg2p-g2pconnect-common-lib \
 && pip install --no-cache-dir git+https://github.com/openg2p/openg2p-g2pconnect-common-lib@v2.0.0\#subdirectory=openg2p-g2pconnect-mapper-lib

# Always from openg2p-g2p-bridge repo (no local installs)
RUN pip install --no-cache-dir \
    "git+https://github.com/openg2p/openg2p-pbms-bg-tasks@${G2P_REF}#subdirectory=openg2p-pbms-models" \
    "git+https://github.com/openg2p/openg2p-pbms-bg-tasks@${G2P_REF}#subdirectory=openg2p-bg-task-models" \
    "git+https://github.com/openg2p/openg2p-pbms-apis@${G2P_REF}#subdirectory=openg2p-pbms-staff-portal-api"

RUN apk del --no-network .build-deps

ENV PYTHONUNBUFFERED=1
ENV BG_TASK_WORKER_TYPE=gunicorn
ENV BG_TASK_HOST=0.0.0.0
ENV BG_TASK_PORT=8000
ENV BG_TASK_NO_OF_WORKERS=8

# Use module path for migrate and Gunicorn WSGI app
CMD python3 -m openg2p_pbms_staff_portal_api.main migrate; \
    ${BG_TASK_WORKER_TYPE} "openg2p_pbms_staff_portal_api.main:app" --workers ${BG_TASK_NO_OF_WORKERS} --worker-class uvicorn.workers.UvicornWorker --bind ${BG_TASK_HOST}:${BG_TASK_PORT}
